name: heat_pass_core
description: Shared core models, repositories, and utilities for HeatPass apps.
version: 0.1.0
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  intl: ^0.19.0

dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^2.5.7
  json_serializable: ^6.9.2